import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
import http from 'node:http';
import {chromium} from 'playwright';
const server=http.createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;const file=path==='/'?'index.html':path.slice(1);if(file.includes('..'))throw Error();const data=await readFile(file);res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(data);}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch();
try{
  const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.route('https://fonts.googleapis.com/**',r=>r.abort());
  await page.route('https://fonts.gstatic.com/**',r=>r.abort());
  await page.goto('http://127.0.0.1:'+server.address().port);
  await page.waitForSelector('body.ux-ready');
  await page.locator('article.week-card:visible').getByRole('tab',{name:'Caderno dos alunos',exact:true}).click();
  await page.locator('#wkPrepare').click();
  assert.equal(await page.locator('article.week-card:visible').getAttribute('data-ux-panel'),'prepare');
  assert.equal(await page.locator('article.week-card:visible .prof-caderno').getAttribute('open'),'');
  assert.equal(await page.locator('article.week-card:visible .prof-panel').isVisible(),true);
  assert.ok((await page.locator('.lesson-quick-nav').boundingBox()).height<90);
  await page.locator('#wkProject').click();
  assert.equal(await page.locator('[data-lesson-material=caderno]').getAttribute('aria-pressed'),'true');
  assert.equal(await page.locator('#projectionPage .student-curriculum').isVisible(),true);
  for(const stage of ['pergunta','conteudo','caderno','atividade','fontes']){
    const b=page.locator('[data-lesson-material='+stage+']');
    const box=await b.boundingBox();assert.ok(box.x>=0&&box.x+box.width<=391,'stage outside mobile viewport');
    await b.click();assert.equal(await b.getAttribute('aria-pressed'),'true');
    assert.equal(await page.locator('#projectionPage .atv-prof').count(),0);
    assert.equal(await page.locator('#projectionPage textarea').count(),0);
    assert.doesNotMatch(await page.locator('#projectionPage').textContent(),/não possui um texto separado/);
  }
  const link=page.locator('#projectionPage .pr-fonte a').first(),url=await link.getAttribute('href');
  assert.ok(url.startsWith('https://'));
  await page.context().route(url,r=>r.fulfill({contentType:'text/html',body:'<h1>Fonte de teste</h1>'}));
  const popupPromise=page.waitForEvent('popup');await link.click();const popup=await popupPromise;
  await popup.waitForLoadState();assert.equal(popup.url(),url);await popup.close();
  assert.equal(await page.locator('[data-lesson-material=fontes]').getAttribute('aria-pressed'),'true');
  await page.locator('[data-lesson-material=caderno]').click();
  const position=await page.locator('#projectionScroll').evaluate(n=>{n.scrollTop=250;return n.scrollTop;});
  await page.locator('[data-lesson-material=fontes]').click();await page.locator('[data-lesson-material=caderno]').click();
  assert.equal(await page.locator('#projectionScroll').evaluate(n=>n.scrollTop),position);
  assert.equal(await page.locator('.lesson-controls,#lessonNext,#lessonPosition').count(),0);
  assert.equal(await page.locator('#projectionWeek option').count(),6);
  await page.locator('[data-lesson-material=conteudo]').click();
  await page.locator('#projectionWeek').selectOption('s9-historia-semana-6');
  assert.equal(await page.locator('[data-lesson-material=conteudo]').getAttribute('aria-pressed'),'true');
  assert.equal(await page.locator('#projectionNext').isDisabled(),true);
  assert.equal(await page.locator('#projectionPrev').isDisabled(),false);
  await page.locator('[data-lesson-material=atividade]').click();
  assert.equal(await page.locator('#projectionPage .atv-aluno').isVisible(),true);
  await page.locator('[data-lesson-material=fontes]').click();
  await page.locator('#projectionPrev').click();
  assert.equal(await page.locator('#projectionWeek').inputValue(),'s9-historia-semana-5');
  assert.equal(await page.locator('[data-lesson-material=fontes]').getAttribute('aria-pressed'),'true');
  await page.locator('[data-lesson-material=caderno]').click();
  await page.locator('[data-lesson-material=pergunta]').click();
  await page.locator('[data-lesson-material=conteudo]').click();
  assert.equal(await page.locator('#projectionPage .atv-aluno').count(),0);
  await mkdir('test-results',{recursive:true});await page.screenshot({path:'test-results/mobile-classroom-sources.png'});
  await page.locator('#projectionClose').click();
  assert.equal(await page.locator('article.week-card:visible').getAttribute('data-ux-panel'),'prepare');
  await page.locator('#wkPrepare').click();
  await page.screenshot({path:'test-results/mobile-teacher-preparation.png'});
  await page.locator('#uxClass').selectOption('s3|3ªB');await page.locator('#uxSubject').selectOption('filosofia');await page.locator('#uxWeekChoices button').nth(2).click();
  await page.reload();await page.waitForSelector('body.ux-ready');await page.locator('#wkProject').click();
  assert.match(await page.locator('#projectionTitle').textContent(),/\S/);
  assert.equal(await page.locator('article.week-card:not(.ux-inactive):not(.hidden)').getAttribute('id'),'s3-filosofia-semana-3');
  assert.equal(await page.locator('[data-lesson-material=caderno]').getAttribute('aria-pressed'),'true');
  assert.deepEqual(errors,[]);
  console.log('PASS one-tap classroom launch, independent materials visible on mobile, student-only content, direct source opening, scroll return, free choice and restored selection');
}finally{await browser.close();await new Promise(r=>server.close(r));}
