import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
vm.runInThisContext(fs.readFileSync('assets/js/gradebook-core.js','utf8'));
const C=globalThis.MaluGradebookCore;
const activities=[{id:'text',valorMax:5,peso:1},{id:'questions',valorMax:10,peso:3}];
assert.equal(C.result(activities,{text:5,questions:5},'ponderada').average,6.25);
assert.equal(C.result(activities,{text:5,questions:5},'aritmetica').average,7.5);
assert.equal(C.result(activities,{text:5},'ponderada').average,2.5);
assert.equal(C.result(activities,{text:5,questions:5}).sum,10);
assert.equal(C.result([...activities,{id:'bonus',extra:true,checklist:true,peso:.2,valorMax:1}],{text:5,questions:5,bonus:1}).average,6.45);
assert.equal(C.result([{id:'check',checklist:true,valorMax:2,peso:1}],{check:1}).sum,2);
assert.equal(C.result([],{}).average,null);
assert.throws(()=>C.result(activities,{text:6}));
const current={turmas:{},alunos:{},mediaModo:{},activities:[{id:'new'}],scores:{p:{new:2}},attendance:{'t|2026-10-08|dia':{p:'P'}}};
const source={turmas:{t:{nome:'Teste'}},alunos:{p:{nome:'Aluno de teste',turmaId:'t'}},mediaModo:{t:'aritmetica'},notasCtrl:{old:{valor:10}},chamadas:{old:{p:'F'}}};
const imported=C.importRoster(source,current);
assert.equal(imported.students,1);assert.equal(imported.next.mediaModo.t,'aritmetica');
assert.deepEqual(imported.next.scores,current.scores);assert.deepEqual(imported.next.attendance,current.attendance);
assert.equal(Object.keys(current.alunos).length,0);assert.equal(imported.next.notasCtrl,undefined);
assert.throws(()=>C.importRoster({alunos:{}},current));
console.log('PASS sums, weighted/arithmetic means, missing scores, bonus, limits and import without previous grades/attendance');
const context={window:{},localStorage:{getItem:()=>null}};vm.createContext(context);
vm.runInContext(fs.readFileSync('assets/js/gradebook-cloud.js','utf8'),context);
const cloud=context.window.MaluGradebookCloud;
const before={version:1,year:2026,bimestre:4,turmas:{},alunos:{},mediaModo:{},activities:[],scores:{p:{a:2,b:3}},attendance:{},importLog:{}};
const after=JSON.parse(JSON.stringify(before));after.scores.p.a=4;
assert.deepEqual(JSON.parse(JSON.stringify(cloud.diff(before,after))),{'scores/p/a':4});
delete after.scores.p.a;assert.deepEqual(JSON.parse(JSON.stringify(cloud.diff(before,after))),{'scores/p/a':null});
assert.equal(cloud.unwire(null).bimestre,4);
vm.runInContext(fs.readFileSync('assets/js/gradebook-arlan.js','utf8'),context);
const roster={turmas:{t:{serie:'1ª série',letra:'A',disciplina:'Filosofia',unidade:'EFG',grade:{4:1}}},alunos:{p:{id:'p',nome:'Ana Maria Silva',turmaId:'t',ativo:true}},attendance:{},importLog:{}};
const csv='data,Turma,Status,Nome_Aluno\n08/10/2026,1A,Falta,Ana Maria Silva\n07/10/2026,1A,Falta,Ana Maria Silva';
const plan=context.window.MaluArlan.plan(csv,roster,'t','2026-10-08',[]);
assert.equal(plan.count,1);assert.equal(plan.next.attendance['t|2026-10-08|dia'].p,'F');
assert.equal(context.window.MaluArlan.plan(csv,plan.next,'t','2026-10-08',[]).count,0);
const marked=JSON.parse(JSON.stringify(roster));marked.attendance['t|2026-10-08|dia']={p:'P'};
assert.equal(context.window.MaluArlan.plan(csv,marked,'t','2026-10-08',[]).count,0);
const ambiguous=JSON.parse(JSON.stringify(roster));ambiguous.alunos.q={id:'q',nome:'Ana Maria Silva',turmaId:'t',ativo:true};
const unresolved=context.window.MaluArlan.plan(csv,ambiguous,'t','2026-10-08',[]);assert.equal(unresolved.count,0);assert.equal(unresolved.pending.length,1);
assert.throws(()=>context.window.MaluArlan.plan(csv,roster,'t','2026-10-07',[]));
console.log('PASS granular cloud updates, deletions, Arlan date boundaries, idempotency, preserved manual calls and ambiguous names');
