import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
import {chromium} from 'playwright';
const files=Object.fromEntries(await Promise.all(['recreio.html','recreio.css','recreio.js','recreio-session.js'].map(async f=>[f,await readFile('percursos/'+f,'utf8')])));
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:390,height:844}}),errors=[];
await context.route('**/*',async r=>{const path=new URL(r.request().url()).pathname.split('/').pop();if(files[path])return r.fulfill({body:files[path],contentType:path.endsWith('.html')?'text/html':path.endsWith('.css')?'text/css':'application/javascript'});return r.abort()});
const writes=[],cloud={};await context.exposeFunction('recordGames',async(path,values)=>{writes.push({path,values});cloud[path]={...(cloud[path]||{}),...values}});
await context.exposeFunction('readGames',path=>cloud[path]||{});
await context.addInitScript(()=>{sessionStorage.setItem('percursos-recreio-profile-v1',JSON.stringify({name:'Ana',turma:'3ª série C',token:'a'.repeat(32),key:'b'.repeat(64)}));const app={name:'percursosRecreio',auth:()=>({currentUser:{uid:'anon'}}),database:()=>({ref:path=>({once:async()=>{const value=await readGames(path);return {val:()=>value}},update:values=>recordGames(path,values)})})};window.firebase={apps:[app],initializeApp:()=>app}});
const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
const token='a'.repeat(32);
async function game(key){await page.locator('[data-game="'+key+'"]').click()}
async function menu(){await page.getByRole('button',{name:'Escolher outro jogo',exact:false}).click()}
const status=()=>page.locator('#feedback').textContent();
try{
 await page.goto('https://percursos.test/recreio.html#turma='+token);
 assert.equal(await page.locator('[data-game]').count(),8);
 assert.equal(await page.locator('#backLessons').getAttribute('href'),'aluno.html#turma='+token);
 await game('logic');await page.getByRole('button',{name:'9',exact:true}).click();assert.match(await status(),/Tente/);await page.getByRole('button',{name:'10',exact:true}).click();assert.match(await status(),/Isso/);await menu();
 await game('words');
 const normalize=text=>text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
 async function solveSearch(count,size){const words=await page.locator('.word-list button').allTextContents(),letters=await page.locator('.word-grid button').allTextContents();assert.equal(words.length,count);assert(words.every(w=>normalize(w).length>=6));assert.equal(letters.length,size*size);const directions=[[0,1],[1,0],[1,1],[1,-1],[0,-1],[-1,0],[-1,-1],[-1,1]];for(const word of words){let path;const answer=normalize(word);for(let start=0;start<letters.length&&!path;start++)for(const [dr,dc]of directions){const r=Math.floor(start/size),c=start%size,coords=Array.from(answer,(_,i)=>[r+dr*i,c+dc*i]);if(coords.some(([y,x])=>y<0||x<0||y>=size||x>=size))continue;const indices=coords.map(([y,x])=>y*size+x);if(indices.map(i=>letters[i]).join('')===answer){path=indices;break}}assert(path,'Missing word '+word);const cells=page.locator('.word-grid button');await cells.nth(path[0]).click();await cells.nth(path.at(-1)).click()}assert.match(await status(),/todas/);assert.equal(await page.locator('.word-list button.found').count(),count);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)}
 await page.getByRole('button',{name:'Dica da palavra',exact:true}).click();assert.match(await status(),/primeira letra/);await page.getByRole('button',{name:'Limpar seleção',exact:true}).click();await solveSearch(5,10);
 await page.getByRole('button',{name:'Desafio',exact:true}).click();await solveSearch(6,12);await menu();
 await game('crossword');
 const puzzles=[['CULTURA','ÉTICA','ARTE'],['HISTÓRIA','TEMPO','PAZ'],['NATUREZA','TERRA','ÁGUA'],['RESPEITO','PAZ','ÉTICA'],['CIÊNCIA','MENTE','ARTE']];
 await page.getByRole('textbox',{name:'Resposta da dica',exact:true}).fill('errado');await page.getByRole('button',{name:'Conferir',exact:true}).click();assert.match(await status(),/Ainda não/);await page.getByRole('button',{name:'Revelar uma letra',exact:true}).click();assert.match(await status(),/revelada/);assert.match(await page.locator('.stone-count').textContent(),/0 de 3/);
 for(let puzzle=0;puzzle<puzzles.length;puzzle++){for(let i=0;i<3;i++){await page.locator('.crossword-clues button').nth(i).click();const answer=(puzzle+i)%2===0?puzzles[puzzle][i].toLowerCase():normalize(puzzles[puzzle][i]);await page.getByRole('textbox',{name:'Resposta da dica',exact:true}).fill(answer);await page.getByRole('button',{name:'Conferir',exact:true}).click();assert.match(await status(),/Isso|completa/)}assert.match(await status(),/Cruzadinha completa/);assert.match(await page.locator('.stone-count').textContent(),/3 de 3/);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);if(puzzle<puzzles.length-1)await page.getByRole('button',{name:'Outra cruzadinha',exact:false}).click()}await menu();
 await game('tic');for(let i=0;i<9;i++){const cell=page.locator('.tic-grid button').nth(i);if(await cell.isEnabled())await cell.click()}assert.match(await status(),/venceu|computador fez|Empate/);await menu();
 await game('hang');for(const letter of ['J','A','N','E','L'])await page.getByRole('button',{name:letter,exact:true}).click();assert.match(await status(),/descobriu: JANELA/);await page.getByRole('button',{name:'Jogar de novo',exact:false}).click();for(const letter of ['B','C','F','H','K','L'])await page.getByRole('button',{name:letter,exact:true}).click();assert.match(await status(),/palavra era AMIZADE/);await menu();
 await game('dots');assert.equal(await page.locator('.dots-edge').count(),24);await page.getByRole('button',{name:'Duas pessoas',exact:true}).click();
 for(const name of ['Linha horizontal, linha 1, coluna 1','Linha vertical, linha 1, coluna 1','Linha horizontal, linha 2, coluna 1','Linha vertical, linha 1, coluna 2'])await page.getByRole('button',{name,exact:true}).click();
 assert.match(await page.locator('.dots-score').textContent(),/Jogador 2: 1/);assert.match(await status(),/joga novamente/);
 for(const line of await page.locator('.dots-edge').all())if(await line.isEnabled())await line.click();assert.equal(await page.locator('.dots-box.dots-player-0, .dots-box.dots-player-1').count(),9);assert.match(await status(),/venceu|Empate/);
 await page.getByRole('button',{name:'Contra o computador',exact:true}).click();for(let i=0;i<24;i++){const line=page.locator('.dots-edge:not(:disabled)').first();if(await line.count())await line.click();else break}assert.equal(await page.locator('.dots-box.dots-player-0, .dots-box.dots-player-1').count(),9);await menu();
 await game('math');
 async function solveMath(){const text=await page.locator('.sequence').textContent(),[,a,op,b]=text.match(/(\d+) ([+−×÷]) (\d+)/);const answer=op==='+'?Number(a)+Number(b):op==='−'?Number(a)-Number(b):op==='×'?Number(a)*Number(b):Number(a)/Number(b);const choices=await page.locator('.choices button').allTextContents();assert.equal(new Set(choices).size,3);assert(choices.includes(String(answer)));const wrong=choices.find(x=>Number(x)!==answer);await page.locator('.choices').getByRole('button',{name:wrong,exact:true}).click();assert.match(await status(),/Tente/);await page.getByRole('button',{name:'Ver dica',exact:true}).click();assert.match(await status(),/Comece|Some|Divida/);await page.locator('.choices').getByRole('button',{name:String(answer),exact:true}).click();assert.match(await status(),/Isso!/);return text}
 const firstMath=await solveMath();await page.getByRole('button',{name:'Próxima conta',exact:false}).click();assert.notEqual(await page.locator('.sequence').textContent(),firstMath);await solveMath();for(const level of ['Médio','Desafio','Fácil']){await page.getByRole('button',{name:level,exact:true}).click();await solveMath()}await menu();
 await page.clock.install();await game('snake');const snake=page.locator('canvas');const initial=await snake.getAttribute('aria-label');await page.getByRole('button',{name:'Começar',exact:true}).click();await page.clock.runFor(460);assert.notEqual(await snake.getAttribute('aria-label'),initial);await page.getByRole('button',{name:'Pausar',exact:true}).click();const paused=await snake.getAttribute('aria-label');await page.clock.runFor(1000);assert.equal(await snake.getAttribute('aria-label'),paused);await page.getByRole('button',{name:'Cima',exact:true}).click();await page.getByRole('button',{name:'Continuar',exact:true}).click();await page.clock.runFor(460);assert.match(await snake.getAttribute('aria-label'),/linha 7/);await page.clock.runFor(5000);assert.match(await status(),/Fim da partida/);await page.getByRole('button',{name:'Jogar de novo',exact:false}).click();assert.match(await status(),/Começar/);await page.getByRole('button',{name:'Começar',exact:true}).click();await menu();await page.clock.runFor(6000);assert.equal(await page.locator('#menu').isVisible(),true);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.waitForFunction(()=>document.getElementById('gameIdentity').textContent.includes('nuvem'));assert(writes.some(w=>w.values.words===true));assert(writes.some(w=>w.values.crossword===true));assert(writes.every(w=>w.path.endsWith('/played')));assert.match(await page.locator('#gameIdentity').textContent(),/Ana/);assert.equal(await page.locator('[data-game=words] .played-badge').count(),1);
 assert.deepEqual(errors,[]);
 await game('logic');await context.setOffline(true);await page.locator('.choices button').first().click();assert.match(await page.locator('#gameIdentity').textContent(),/aguardando internet/);await context.setOffline(false);await page.waitForFunction(()=>document.getElementById('gameIdentity').textContent.includes('nuvem'));await menu();
 await page.evaluate(()=>localStorage.removeItem('percursos-games-played-v1'));await page.reload();await page.waitForFunction(()=>document.querySelector('[data-game=words] .played-badge'));assert.equal(await page.locator('[data-game=crossword] .played-badge').count(),1);
 const guest=await browser.newContext({viewport:{width:390,height:844}});await guest.route('**/*',async r=>{const path=new URL(r.request().url()).pathname.split('/').pop();if(files[path])return r.fulfill({body:files[path],contentType:path.endsWith('.html')?'text/html':path.endsWith('.css')?'text/css':'application/javascript'});return r.abort()});const guestPage=await guest.newPage();await guestPage.goto('https://percursos.test/recreio.html#turma='+token);assert.equal(await guestPage.locator('#menu').isVisible(),false);assert.match(await guestPage.locator('#gameIdentity').textContent(),/selecione sua turma e seu nome/);assert.equal(await guestPage.getByRole('link',{name:'Identificar-me e entrar'}).getAttribute('href'),'aluno.html#turma='+token);await guest.close();
 await mkdir('test-results',{recursive:true});await page.screenshot({path:'test-results/percursos-recreio-mobile.png',fullPage:true});
 console.log('PASS eight mobile games; harder random word searches and both levels; five connected crosswords, hints and accent normalization; dots squares, extra turn, two-player and computer matches; varied calculations, hints and three levels; snake movement, pause, direction, collision, restart and exit; class link preserved; no overflow or JS errors');
}finally{await browser.close()}

