import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
import http from 'node:http';
import {chromium} from 'playwright';
const server=http.createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname,file=path==='/'?'index.html':path.slice(1);res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(await readFile(file));}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch();
try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**',r=>r.abort());await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForSelector('body.ux-ready');
 const choices=page.locator('.ux-direct-selectors');assert.equal(await choices.locator('button').count(),7);
 await choices.locator('[data-choice=s3]').click();await choices.locator('[data-choice=filosofia]').click();assert.equal(await page.locator('article.week-card:visible').getAttribute('id'),'s3-filosofia-semana-1');
 assert.equal(await choices.locator('[data-choice=s3]').getAttribute('aria-pressed'),'true');assert.equal(await choices.locator('[data-choice=filosofia]').getAttribute('aria-pressed'),'true');
 await page.reload();await page.waitForSelector('body.ux-ready');assert.equal(await choices.locator('[data-choice=filosofia]').getAttribute('aria-pressed'),'true');
 await choices.locator('[data-choice=s9]').click();assert.equal(await choices.locator('[data-choice=filosofia]').isDisabled(),true);assert.equal(await choices.locator('[data-choice=historia]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('article.week-card:visible').getAttribute('id'),'s9-historia-semana-1');
 await choices.locator('[data-choice=s3]').click();await choices.locator('[data-choice=filosofia]').click();
 for(const width of [320,390,430,1280]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));const rows=await choices.locator('.ux-choice-row').evaluateAll(ns=>ns.map(n=>n.getBoundingClientRect().height));assert.ok(rows.every(h=>h<=44));const buttons=await choices.locator('button').evaluateAll(ns=>ns.map(n=>({width:n.clientWidth,scroll:n.scrollWidth})));assert.ok(buttons.every(n=>n.scroll<=n.width+1),'labels overflow at '+width);}
 await page.setViewportSize({width:390,height:844});await mkdir('test-results',{recursive:true});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'test-results/direct-selectors-mobile.png'});
 assert.equal(await page.locator('article.week-card:visible .prof-caderno').getAttribute('open'),'');assert.ok(await page.locator('article.week-card:visible .ux-glossary').isVisible());
 const before=await page.evaluate(()=>JSON.stringify({...localStorage}));await page.locator('#wkProject').click();await page.locator('[data-lesson-material=esquema]').click();assert.equal(await page.locator('#projectionPage .ux-board-concept').count(),3);assert.equal(await page.locator('#projectionPage .prof-panel').count(),0);await page.screenshot({path:'test-results/board-concepts-mobile.png'});await page.locator('#projectionClose').click();
 await page.evaluate(()=>window.print=()=>{});await page.locator('#navTools').evaluate(n=>n.open=true);await page.locator('#uxPrintCurrent').click();await page.locator('[data-print-kind="prepare"]').click();assert.equal(await page.locator('.ux-print-selected').count(),1);assert.equal(await page.locator('.ux-print-selected').getAttribute('id'),'s3-filosofia-semana-1');await page.emulateMedia({media:'print'});assert.equal(await choices.isVisible(),false);assert.ok(await page.locator('.ux-print-selected .ux-print-note-space').isVisible());assert.ok(await page.locator('.ux-print-selected .ux-study').isVisible());await page.pdf({path:'test-results/weekly-teacher-route.pdf',format:'A4',printBackground:true});await page.evaluate(()=>window.dispatchEvent(new Event('afterprint')));await page.emulateMedia({media:'screen'});assert.equal(await page.locator('article.week-card:visible').count(),1);assert.equal(await page.evaluate(()=>JSON.stringify({...localStorage})),before);assert.deepEqual(errors,[]);console.log('PASS direct selectors, state restoration, 9th grade availability, compact mobile rows, open preparation, concept layout and clean weekly teacher print');
}finally{await browser.close();await new Promise(r=>server.close(r));}
