(function(){
'use strict';
const sessionKey='percursos-recreio-profile-v1',localKey='percursos-games-played-v1',pendingKey='percursos-games-pending-v1';
const games={logic:'Lógica',words:'Caça-palavras',crossword:'Palavras cruzadas',tic:'Jogo da velha',hang:'Forca',dots:'Pontinho',math:'Pequenos cálculos',snake:'Cobrinha'};
const read=(key,fallback,storage=localStorage)=>{try{return JSON.parse(storage.getItem(key))||fallback}catch(e){return fallback}};
const profile=read(sessionKey,null,sessionStorage),token=new URLSearchParams(location.hash.slice(1)).get('turma')||'';
const ready=!!profile&&typeof profile.name==='string'&&profile.name.trim().length>0&&/^[123]ª série [ABC]$/.test(profile.turma)&&profile.token===token&&(!token||(/^[a-f0-9]{32}$/.test(token)&&/^[a-f0-9]{64}$/.test(profile.key)));
const status=document.getElementById('gameIdentity');
window.PercursosRecreio={ready,played};
if(!ready){document.getElementById('menu').hidden=true;status.textContent='Para registrar seus jogos, selecione sua turma e seu nome primeiro.';const link=document.createElement('a');link.href='aluno.html'+location.hash;link.textContent='Identificar-me e entrar';link.className='register-games';status.appendChild(document.createElement('br'));status.appendChild(link);return}
const identity=token?token+'/'+profile.key:profile.turma+'/'+profile.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
let app=null,busy=null,writeFailed=false;const gameNames=()=>Object.keys(read(localKey,{})[identity]||{}).filter(k=>games[k]).map(k=>games[k]);
function show(message){status.textContent=profile.name+' · '+profile.turma+' · '+message;document.querySelectorAll('[data-game]').forEach(b=>{const played=read(localKey,{})[identity]?.[b.dataset.game];let badge=b.querySelector('.played-badge');if(played&&!badge){badge=document.createElement('span');badge.className='played-badge';badge.textContent='✓ Jogado';b.appendChild(badge)}})}
function persist(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch(e){writeFailed=true;show('Não foi possível salvar neste aparelho.');return false}}
function played(key){if(!games[key])return;const all=read(localKey,{});all[identity]??={};all[identity][key]=true;const localSaved=persist(localKey,all);if(token){const pending=read(pendingKey,{}),route='classTracks/'+token+'/students/'+profile.key+'/played';pending[route]??={};pending[route][key]=true;persist(pendingKey,pending);flush()}else if(localSaved)show('Jogos registrados neste aparelho: '+gameNames().join(', ')+'.')}
async function connect(){if(!window.firebase)throw Error('Conexão indisponível');if(!app){const config={apiKey:'AIzaSyDjxPzcMZcnW679kERfSkMOFY98Ncrtd58',authDomain:'percursos-754d6.firebaseapp.com',databaseURL:'https://percursos-754d6-default-rtdb.firebaseio.com',projectId:'percursos-754d6',appId:'1:304874200719:web:e05949c4c71d40a542dafa'};app=firebase.apps.find(a=>a.name==='percursosRecreio')||firebase.initializeApp(config,'percursosRecreio')}if(!app.auth().currentUser)await app.auth().signInAnonymously();return app}
async function flush(){if(!token||busy)return busy;if(!navigator.onLine){show('Salvo neste aparelho · aguardando internet.');return false}busy=(async()=>{try{const a=await connect();while(true){const pending=read(pendingKey,{});if(!Object.keys(pending).length)break;for(const [route,values]of Object.entries(pending)){await a.database().ref(route).update(values);const fresh=read(pendingKey,{});for(const key of Object.keys(values))delete fresh[route]?.[key];if(!Object.keys(fresh[route]||{}).length)delete fresh[route];if(!persist(pendingKey,fresh))return false}}if(!writeFailed)show('Jogos registrados na nuvem ✓');return true}catch(e){show('Salvo neste aparelho · registro na nuvem pendente.');return false}})().finally(()=>busy=null);return busy}
show('Seus jogos serão registrados quando você jogar.');
if(token)(async()=>{try{const a=await connect(),snapshot=await a.database().ref('classTracks/'+token+'/students/'+profile.key+'/played').once('value'),all=read(localKey,{});all[identity]={...(all[identity]||{}),...(snapshot.val()||{})};persist(localKey,all);await flush()}catch(e){show('Seus jogos serão salvos neste aparelho até a conexão voltar.')}})();
window.addEventListener('online',flush);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')flush()});
})();
